[general]
import = ["catppuccin-mocha.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 11

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[mouse]
hide_when_typing = true
