icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 2
format_alt = " $icon $frequency "
[[block.click]]
button = "right"
cmd = "alacritty -e btop"

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "

[[block]]
block = "net"
format = " $icon {$ssid|Wired} "
format_alt = " $icon $ip "
[[block.click]]
button = "right"
cmd = "alacritty -e doas iwctl"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "
not_charging_format = " $icon 󰚥 $percentage "
interval = 5

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "scratchpad"
