#!/bin/sh

choice=$(echo -e "poweroff\nreboot\nsuspend\nhibernate\nhybrid-sleep\nlogout" | wmenu -b -i -n cdd6f4 -N 1e1e2e -s 1e1e2e -S cba6f7 -m 000000 -M cba6f7 -f 'JetBrainsMono Nerd Font 11')

brightnessctl g > $HOME/.cache/brightness

case "$choice" in
  "poweroff") loginctl poweroff
  ;;
  "reboot") loginctl reboot
  ;;
  "suspend") loginctl suspend
  ;;
  "hibernate") loginctl hibernate
  ;;
  "hybrid-sleep") loginctl hybrid-sleep
  ;;
  "logout") swaymsg exit 
  ;;
  *) exit 1
  ;;
esac
